### ISSUE TITLE
UNSAT exception design

### ISSUE THREAD

**Issue by pradyunsg** [sarugaku/resolvelib#31]
I've been thinking about the unsat exception to be raised and, basically, I think it might be a good idea to expose 2 optional methods to:

- get the equivalent of learned clauses, that we could feed back into the system.
- get a human readable explanation of the situation.

Both are optional, but I imagine that resolution algorithms are capable of these outputs and surfacing them via a standard mechanism might make sense. YAGNI possibly applied here, but I'm fairly certain that the human-readable messaging makes sense on its own anyway. A clear standard / documentation on how/what it could be would be nice to have.

**Comment by pradyunsg** [comment]
@pfmoore @uranusjr notes from a past @pradyunsg about what to do for the ResolutionImpossible exception. :3

**Comment by uranusjr** [comment]
Personally I don’t think it’s the library’s place to provide a human-readable output. `ResolutionImpossible` is intended to be caught and handled by the outer call stack, and therefore should provide structured information, not rendered. It may be worthwhile to have a module like `resolvelib.debugging` that formats an exception into pretty output for debugging purposes, but I feel that should not live directly on the exception type.

I think it’s a good idea for the exception to have the state in the resolver. But this needs to be done extremely carefully and in an abstract way, and not tied with the backtracking nature of the resolver. Otherwise it will be impossible to change the resolution internals without the caller knowing, which is an important goal to this project.

**Comment by pradyunsg** [comment]
Closing this out since I think we've figured this out. For posterity, I recently described what we did for this in https://github.com/spack/spack/issues/36502#issuecomment-1487614685.
