### ISSUE TITLE
resolution fails for 'django'

### ISSUE THREAD

**Issue by DavHau** [sarugaku/resolvelib#33]
On current master (rev. 243acc576eae9f8bbd2fafa25653f3a7db2efc52).
Executing `pypi_wheel_provider.py django` fails with:
`resolvelib.resolvers.ResolutionTooDeep: 100`

**Comment by uranusjr** [comment]
The current pip master can successfully install:

```
$ python src/pip install --unstable-feature=resolver django
Collecting Django==3.0.4
  Downloading Django-3.0.4-py3-none-any.whl (7.5 MB)
     |████████████████████████████████| 7.5 MB 1.6 MB/s
Collecting sqlparse==0.3.1
  Downloading sqlparse-0.3.1-py2.py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 2.5 MB/s
Collecting asgiref==3.2.7
  Downloading asgiref-3.2.7-py2.py3-none-any.whl (19 kB)
Collecting pytz==2019.3
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Installing collected packages: sqlparse, pytz, asgiref, Django
Successfully installed Django-3.0.4 asgiref-3.2.7 pytz-2019.3 sqlparse-0.3.1
```

Which leads me to think this is a bug in the example provider implementation, not the resolver. The resolver should likely have produced a better exception though.

I’ll look into this. Thanks for the report.

**Comment by uranusjr** [comment]
I found the problem; the example resolver does not handle [name normalisation](https://www.python.org/dev/peps/pep-0503/#normalized-names) correctly. Django is one of the projects published under an unnormalised name. The resolver is stuck at keep asking for matches for `Django`, but the provider keeps giving it `django`.

I will commit a fix for this, but first let me see why the resolver got stuck here (it should probably realise it’s stucked right when it tries the same package for the second time, instead of chasing its tail until running out of time.

**Comment by uranusjr** [comment]
(Actually I think the Django django situation is the other way around, but whatever.)
